notifications:
  email: false

sudo: false
language: python

# Linux with different python versions
python:
  - "2.7"
  - "3.6"

# Include Other operating systems
matrix:
    include:
        - name: "Linux with Python: pypy"
          os: linux
          python: "pypy"
          before_install:
            - python --version
            - python -m pip install --upgrade pip
            - curl -L -O https://download.lfd.uci.edu/pythonlibs/x2tqcw5k/numpy-1.19.2+mkl-cp39-cp39-win_amd64.whl
            - curl -L -O https://download.lfd.uci.edu/pythonlibs/x2tqcw5k/scipy-1.5.3-cp39-cp39-win_amd64.whl
            - python -m pip install numpy-1.19.2+mkl-cp39-cp39-win_amd64.whl
            - python -m pip install scipy-1.5.3-cp39-cp39-win_amd64.whl
            - python -m pip install --upgrade pytest-cov
            - python -m pip install codecov

        - name: "Linux with Python: pypy3"
          os: linux
          sudo: true
          python: "pypy3"
          before_install:
            - sudo add-apt-repository universe
            - sudo apt update
            - sudo apt install gfortran libopenblas-dev liblapack-dev python-dev
            - python --version
            - python -m pip install --upgrade pip
            - python -m pip install --upgrade pytest-cov
            - python -m pip install codecov

        - name: "macOSX with Python: 2.7"
          os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=2.7

        - name: 'macOSX with Python: 3.6'
          os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=3.6

        - name: "Windows with Python: 3.8"
          os: windows
          language: shell
          before_install:
            - choco install python --version 3.8.0
            - python --version
            - python -m pip install --upgrade pip
            - python -m pip install --upgrade pytest-cov
            - python -m pip install codecov
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

before_install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade pytest-cov
  - python -m pip install codecov

install:
  - python -m pip install -r requirements.txt
  - python -m pip install -e .

script:
  - python -m pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
