notifications:
  email: false

sudo: false
language: python

python:
  - "3.6"

install:
  - python --version
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install -e .

script:
  - pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
