notifications:
  email: false

sudo: false
language: python

matrix:
    include:
        - name: "Linux"
          os: linux
          python:
            - "2.7"
            - "3.6"
            - "pypy"
            - "pypy3"
        - name: "macOSX"
          os: osx
          osx_image: xcode11
          language: shell
        - name: "Windows"
          os: windows
          language: shell
          before_install:
            - choco install python 
            - python --version
            - python -m pip install --upgrade pip
          env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

# before_install:
install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -e .

# install:
#   - pip install -r requirements.txt
#   - pip install -e .

script:
  - pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
