language: python

python:
  - "3.6"      # current default Python on Travis CI
 
  - "nightly"
install:
  - python --version
  - pip install -r requirements.txt

script:
  - python GeenerageOrthogonalFunctions.py
