notifications:
  email: false

sudo: false
language: python

# Linux with different python versions
python:
  - "2.7"
  - "3.6"
  - "pypy"
  - "pypy3"

# Include OSX
matrix:
    include:
        - os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=2.7
        - os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=3.6

before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
