notifications:
  email: false

dist: xenial
sudo: false
language: python

python:
  - "3.6"

install:
  - python --version
  - pip install -r requirements.txt
  - pip install pytest-cov codecov

script:
  - pytest -s GenerateOrthogonalFunctions.py

env:
    - CODECOV_TOKEN=83520502-cad9-475e-b4c8-8d120acc1243

after_success:
  - codecov
