notifications:
  email: false

sudo: false
language: python

# Linux with different python versions
python:
  - "2.7"
  - "3.6"

# Include OSX
matrix:
    include:
        - os: linux
          sudo: true
          python: "pypy3"
          before_install:
            - sudo apt install gfortran libopenblas-dev liblapack-dev python-dev
        - os: linux
          python: "pypy"
          before_install:
            - pip install --upgrade pip
            - wget https://download.lfd.uci.edu/pythonlibs/x2tqcw5k/numpy-1.19.2+mkl-cp39-cp39-win_amd64.whl
            - wget https://download.lfd.uci.edu/pythonlibs/x2tqcw5k/scipy-1.5.3-cp39-cp39-win_amd64.whl
            - pip install numpy-1.19.2+mkl-cp39-cp39-win_amd64.whl
            - pip install scipy-1.5.3-cp39-cp39-win_amd64.whl
        - os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=2.7
        - os: osx
          osx_image: xcode11
          language: shell
          env: PYTHON_VERSION=3.6
        - os: windows
          language: shell
          before_install:
            - choco install python --version 3.8.0
            - python -m pip install --upgrade pip
            - python -m pip install numpy
            - python -m pip install scipy
          env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

before_install:
  - python --version
  - pip install --upgrade pip
  - pip install --upgrade pytest-cov
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest --cov-report=xml --cov=tests/

after_success:
  - codecov
